# 画面のサイズ
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# 一塁〜三塁ベースのサイズ
BASE_WIDTH = 16
BASE_HEIGHT = 16
HOME_BASE_WIDTH = BASE_WIDTH // 4 * 3
HOME_BASE_HEIGHT = BASE_HEIGHT // 4 * 3

# スコアカウンターの設定
SCORE_COUNTER_WIDTH = SCREEN_WIDTH//10
SCORE_COUNTER_HEIGHT = SCREEN_HEIGHT//6
SCORE_COUNTER_X = 0
SCORE_COUNTER_Y = SCREEN_HEIGHT-SCORE_COUNTER_HEIGHT

# SBOカウンターの設定
SBO_COUNTER_WIDTH = SCREEN_WIDTH//8
SBO_COUNTER_HEIGHT = SCREEN_HEIGHT//6
SBO_COUNTER_X = SCREEN_WIDTH-SBO_COUNTER_WIDTH
SBO_COUNTER_Y = SCREEN_HEIGHT-SBO_COUNTER_HEIGHT

# ボールの半径
BALL_RADIUS = 4

# プレイヤーの半径
PLAYER_RADIUS = 6

# フォント
FONT_PATH = 'Nosutaru-dotMPlusH-10-Regular.ttf'
FONT_SIZE = 32

# 色の定義
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 128, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 215, 0)
BROWN = (139, 69, 19)
LIGHT_BROWN = (222, 184, 135)

BALL_COLOR = (230, 215, 150)